[workspace]
resolver = "3"
members = [
    "library",
    "server"
]

[workspace.package]
version = "0.0.1"
authors = [
    "Tommy Bagan"
]
edition = "2024"

[workspace.dependencies]
tonic = "0.14.2"
iso_currency = "0.5.3"
chrono = "0.4.42"